# Count gene expression annotations
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX ps: <http://purl.org/phenoscape/vocab.owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX GeneExpression: <http://purl.obolibrary.org/obo/GO_0010467>
PREFIX Zebrafish: <http://purl.obolibrary.org/obo/NCBITaxon_7955>
PREFIX Mouse: <http://purl.obolibrary.org/obo/NCBITaxon_10090>
PREFIX X_laevis: <http://purl.obolibrary.org/obo/NCBITaxon_8355>
PREFIX X_tropicalis: <http://purl.obolibrary.org/obo/NCBITaxon_8364>

SELECT (COUNT (DISTINCT ?annotation) AS ?count)
FROM <http://kb.phenoscape.org/>
WHERE 
{ 
?annotation rdf:type GeneExpression: .
?annotation ps:associated_with_taxon Zebrafish: .
}
