#For Characiformes:  species, family, order, collection code, collection number, phenotype (EQ)
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ps: <http://purl.org/phenoscape/vocab.owl#>
PREFIX has_character: <http://purl.obolibrary.org/obo/CDAO_0000142>
PREFIX has_state: <http://purl.obolibrary.org/obo/CDAO_0000184>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX ow: <http://purl.org/phenoscape/owlet/syntax#>
PREFIX PelvicFin: <http://purl.obolibrary.org/obo/UBERON_0000152>
PREFIX PectoralFin: <http://purl.obolibrary.org/obo/UBERON_0000151>
PREFIX part_of: <http://purl.obolibrary.org/obo/BFO_0000050>
PREFIX belongs_to_tu: <http://purl.obolibrary.org/obo/CDAO_0000191>
PREFIX has_external_reference: <http://purl.obolibrary.org/obo/CDAO_0000164>
PREFIX Characiformes: <http://purl.obolibrary.org/obo/VTO_0037519>
PREFIX dwc: <http://rs.tdwg.org/dwc/terms/>
PREFIX Family: <http://purl.obolibrary.org/obo/TAXRANK_0000004>
PREFIX Order: <http://purl.obolibrary.org/obo/TAXRANK_0000003>

SELECT (STR(?taxon) AS ?taxon_id) (STR(?taxon_label) AS ?taxon_name) (STR(?order_label) AS ?order_name) (STR(?family_label) AS ?family_name) (STR(?collection) AS ?collection_code) (STR(?catalog_number) AS ?cat_number) (COUNT(DISTINCT ?phenotype) AS ?phenotype_count)
FROM <http://kb.phenoscape.org/>
FROM <http://purl.obolibrary.org/obo/tto.owl>
WHERE
{	
?cell has_state: ?state .
?cell belongs_to_tu: ?otu .
?otu has_external_reference: ?taxon .
?taxon rdfs:label ?taxon_label .
?taxon rdfs:subClassOf* ?vto_family .
?vto_family rdfs:label ?family_label .
?vto_family oboInOwl:hasDbXref ?xref .
?tto_family oboInOwl:hasDbXref ?xref .
?tto_family <http://purl.obolibrary.org/obo/tto#has_rank> Family: .
?taxon rdfs:subClassOf* ?vto_order .
?vto_order rdfs:label ?order_label .
?vto_order oboInOwl:hasDbXref ?xref .
?tto_order oboInOwl:hasDbXref ?xref .
?tto_order <http://purl.obolibrary.org/obo/tto#has_rank> Order: .
?state ps:describes_phenotype ?phenotype .
?otu dwc:individualID ?specimen .
?specimen dwc:collectionID/rdfs:label ?collection .
?specimen dwc:catalogNumber ?catalog_number .
}
GROUP BY ?taxon ?taxon_label ?order_label ?family_label ?collection ?catalog_number